// <auto-generated />
using AuthorizationService;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AccountDatabaseAccess.Migrations
{
    [DbContext(typeof(UserDataContext))]
    [Migration("20250509074710_InitializeAccountDatabase")]
    partial class InitializeAccountDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AccountsModelClasses.Adress", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("ApartmentNumber")
                        .HasColumnType("integer")
                        .HasColumnName("apartment_number");

                    b.Property<int>("BuildingNumber")
                        .HasColumnType("integer")
                        .HasColumnName("building_number");

                    b.Property<string>("Liter")
                        .HasColumnType("text")
                        .HasColumnName("liter");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("region");

                    b.Property<string>("Settlement")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("settlement");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("street_name");

                    b.HasKey("Id");

                    b.ToTable("adress");
                });

            modelBuilder.Entity("AccountsModelClasses.ShopppingCart", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("shopping_cart");
                });

            modelBuilder.Entity("AccountsModelClasses.ShopppingCartItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("CartId")
                        .HasColumnType("bigint")
                        .HasColumnName("cart_id");

                    b.Property<long>("Count")
                        .HasColumnType("bigint")
                        .HasColumnName("count");

                    b.Property<long>("ProductItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("product_item_id");

                    b.HasKey("Id");

                    b.HasIndex("CartId");

                    b.ToTable("shopping_cart_item");
                });

            modelBuilder.Entity("AccountsModelClasses.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("hashed_passsword");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.HasKey("Id");

                    b.ToTable("user");
                });

            modelBuilder.Entity("AccountsModelClasses.UserAdress", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<long>("AdresssId")
                        .HasColumnType("bigint")
                        .HasColumnName("adress_id");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("id_default");

                    b.HasKey("UserId", "AdresssId");

                    b.HasIndex("AdresssId");

                    b.ToTable("user_adress");
                });

            modelBuilder.Entity("AccountsModelClasses.UserPaymentMethod", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BankCardLastNumbers")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("bank_card_last_numbers");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean")
                        .HasColumnName("id_default");

                    b.Property<string>("PaymentAgregatorCardId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payment_agregator_user_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_payment_method");
                });

            modelBuilder.Entity("AccountsModelClasses.ShopppingCart", b =>
                {
                    b.HasOne("AccountsModelClasses.User", "User")
                        .WithMany("ShopppingCarts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_shopping_cart_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AccountsModelClasses.ShopppingCartItem", b =>
                {
                    b.HasOne("AccountsModelClasses.ShopppingCart", "ShopppingCart")
                        .WithMany("Items")
                        .HasForeignKey("CartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_shopping_cart_item_shopping_cart_id");

                    b.Navigation("ShopppingCart");
                });

            modelBuilder.Entity("AccountsModelClasses.UserAdress", b =>
                {
                    b.HasOne("AccountsModelClasses.Adress", "Adress")
                        .WithMany("UserAdresses")
                        .HasForeignKey("AdresssId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_adress_user_id");

                    b.HasOne("AccountsModelClasses.User", "User")
                        .WithMany("UserAdresses")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_adress_user_id");

                    b.Navigation("Adress");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AccountsModelClasses.UserPaymentMethod", b =>
                {
                    b.HasOne("AccountsModelClasses.User", "User")
                        .WithMany("UserPaymentMethods")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_user_payment_method_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AccountsModelClasses.Adress", b =>
                {
                    b.Navigation("UserAdresses");
                });

            modelBuilder.Entity("AccountsModelClasses.ShopppingCart", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AccountsModelClasses.User", b =>
                {
                    b.Navigation("ShopppingCarts");

                    b.Navigation("UserAdresses");

                    b.Navigation("UserPaymentMethods");
                });
#pragma warning restore 612, 618
        }
    }
}
